<a href="https://colab.research.google.com/github/noushadkhan01/Projects/blob/master/Deep-Learning/SOM/Credit_Card_Defaulter_prediction_using_SOM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
df = pd.read_csv('https://bit.ly/2qRlRO7')
df.head()

CustomerID  A1     A2     A3  A4  A5  A6     A7  A8  A9  A10  A11  A12  \
0    15776156   1  22.08  11.46   2   4   4  1.585   0   0    0    1    2   
1    15739548   0  22.67   7.00   2   8   4  0.165   0   0    0    0    2   
2    15662854   0  29.58   1.75   1   4   4  1.250   0   0    0    1    2   
3    15687688   0  21.67  11.50   1   5   3  0.000   1   1   11    1    2   
4    15715750   1  20.17   8.17   2   6   4  1.960   1   1   14    0    2   

   A13   A14  Class  
0  100  1213      0  
1  160     1      0  
2  280     1      0  
3    0     1      1  
4   60   159      1

In [0]:
df.shape

(690, 16)

# KMeans Cluster

In [0]:
from sklearn.cluster import KMeans

In [0]:
X = df.iloc[:, 1:-1]
X.head(1)

A1     A2     A3  A4  A5  A6     A7  A8  A9  A10  A11  A12  A13   A14
0   1  22.08  11.46   2   4   4  1.585   0   0    0    1    2  100  1213

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:
sc = MinMaxScaler()
X = sc.fit_transform(X)
X[:2]

array([[1.        , 0.12526316, 0.40928571, 0.5       , 0.23076923,
        0.375     , 0.05561404, 0.        , 0.        , 0.        ,
        1.        , 0.5       , 0.05      , 0.01212   ],
       [0.        , 0.13413534, 0.25      , 0.5       , 0.53846154,
        0.375     , 0.00578947, 0.        , 0.        , 0.        ,
        0.        , 0.5       , 0.08      , 0.        ]])

In [0]:
model = KMeans(2)
model

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [0]:
model.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [0]:
labels = model.labels_
labels[:2]

array([0, 0], dtype=int32)

In [0]:
labels.shape

(690,)

In [0]:
y = df.Class
y[:2], y.shape

(0    0
 1    0
 Name: Class, dtype: int64, (690,))

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [0]:
confusion_matrix(y, labels)

array([[306,  77],
       [ 23, 284]])

In [0]:
print(classification_report(y, labels))

             precision    recall  f1-score   support

          0       0.93      0.80      0.86       383
          1       0.79      0.93      0.85       307

avg / total       0.87      0.86      0.86       690



# SOM